### ISSUE TITLE
 attempt to index local 'msg' (a userdata value)

### ISSUE THREAD

**Issue by cokeboL** [zhanjunxiong/luapb#1]
hi，先感谢老兄，这个项目真棒！

但是使用的时候遇到问题，我在cocos2dx中集成了luapb，运行时先依照test.lua编写了test.proto，然后运行。如果我首先调用test.lua里的代码，会打印出正确的结果，但是如果我调用了cocos2dx绑定的那些（用tolua绑定，还有些ui操作什么的）就会报错" attempt to index local 'msg' (a userdata value)"
请教老兄，这个可能是怎么引起的，有什么解决办法比较好？

非常感谢！

**Comment by cokeboL** [comment]
我又调试了下，可能是gc导致的。我在lua中调用collectgarbage相关的函数则会导致出错，不调用则可以正常解析

**Comment by cokeboL** [comment]
这个问题解决了，不要调用collectgarbage("collect")就好

**Comment by bingtian** [comment]
请问，你在cocos2dx中是怎么设置proto的路径的？

**Comment by cokeboL** [comment]
把你proto所在的文件夹addSearchPath就行了

**Comment by cokeboL** [comment]
把你proto所在的文件夹addSearchPath就行了

**Comment by bingtian** [comment]
这个add了，跟luapb没关系的吧，我试过将绝对路径写上也没用

**Comment by cokeboL** [comment]
真机吗？真机的assetsmanager是有问题的，fullpath返回的是assets下的相对路径，protobuf里用open、fopen这些，需要绝对路径。你可以在import的时候，getStringFromFile，然后再写入到writable path下面的同名文件，然后再给protobuf使用

**Comment by bingtian** [comment]
android的确实是assets下的相对路径，不过ios和mac是返回绝对路径的，也是不行
你是在android上测试的？ios都测试过吗？

**Comment by bingtian** [comment]
我平时开发是直接编译mac版本的，用的就是mac的绝对路径也不行，真蛋疼啊

**Comment by cokeboL** [comment]
android，ok，ios我没测，应该没问题吧，你加点打印跟下，解决了求反馈

**Comment by bingtian** [comment]
问题已解决。
我发到这里去了，https://github.com/zhanjunxiong/luapb/issues/3
