### ISSUE TITLE
repeated filed，多次add有问题

### ISSUE THREAD

**Issue by cokeboL** [zhanjunxiong/luapb#2]
require("luapb");

--package lm;
--message test
--{
--  required int32 uid = 1;
--  required int32 param = 2;
--  optional string param1 = 3;
--  repeated string param2 = 4;
--};

pb.import("test.proto");

function testAdd()
    local msg = pb.new("lm.test");
    msg.uid = 12345;
    msg.param = 9876;
    msg.param1 = "zjx";
    --print("type: " .. type(msg.param2));
    msg.param2.add("first");
    msg.param2.add("second");
    msg.param2.add("three");

```
print("uid: " .. msg.uid);
print("param: " .. msg.param);
print("param1: " .. msg.param1);

for i = 1, msg.param2.len() do
    local value = msg.param2[i];
    print("i: " .. i .. " value: " .. value); 
end
print("str: " .. pb.tostring(msg));
print("hello world");
```

end
testAdd()
testAdd()

封装成函数的时候，多次调用，repeated filed的个数会和之前调用的累加，比如这个函数里
        msg.param2.add("first");
    msg.param2.add("second");
    msg.param2.add("three");
第一次调用testAdd()执行了add了三次， msg.param2.len() 为3
第二次调用testAdd()又执行了add了三次， 局部作用域，msg.param2.len() 应该为3，但实际为6

**Comment by zhanjunxiong** [comment]
这个问题 和 不能gc的问题已经修复，你在试试看

**Comment by cokeboL** [comment]
好的，我去试试，老兄辛苦了，多谢！

**Comment by zhanjunxiong** [comment]
改了语法了

**Comment by zhanjunxiong** [comment]
你看一下test.lua

**Comment by cokeboL** [comment]
好的

**Comment by cokeboL** [comment]
我加了点更详细的测试项，功能完善，没有再发现新的bug，应该是ok了的。
我之前用网易的那个proto-gen-lua，每次要生成好多lua代码，有些限制需要绕，很麻烦。
如果没有老兄对bug的及时修复，我这两天的集成和bug定位就心血白费了，
现在有了你这个项目，我们项目以后可以节省不少体力。
非常感谢老兄无私分享的精神和负责的态度，真的很棒！！！

**Comment by cokeboL** [comment]
下面的两条是我进行测试的proto文件和lua代码，希望对其他人有所帮助

**Comment by cokeboL** [comment]
// file:  test.proto

package person;

message personInfo
{
    required int32  id = 1;
    required string name = 2;
};

message persons
{
    required int32 uid = 1; 
    required string uname = 5;
    optional string udescription = 3;
    repeated string strs = 2;
    repeated personInfo persons = 4;
};

**Comment by cokeboL** [comment]
// file:  testLuapb.lua

local pb = require("pb");
pb.import("test.proto");

local pbn = 1
function testpb()
    print("***********************************************************")
    print("----pb n: ", pbn);
    pbn = pbn+1

```
local msg = pb.new("person.persons");
msg.uid = 10000+pbn;
msg.uname = "uname--";
msg.udescription = "udescription..";
msg.strs:add("str1");
msg.strs:add("str2");
msg.strs:add("str3");

local pInfo
msg.persons:add();
pInfo = msg.persons:get(1);
pInfo.id = 10001
pInfo.name = "person 001"

msg.persons:add();
pInfo = msg.persons:get(2);
pInfo.id = 10002
pInfo.name = "person 002"

print("uid: " .. msg.uid);
print("uname: " .. msg.uname);
print("udescription: " .. msg.udescription);

for i = 1, msg.strs:len() do
    print("str " .. i .. " : " .. msg.strs:get(i)); 
end

for i = 1, msg.persons:len() do
    print("id " .. i .. " : " .. msg.persons:get(i).id); 
    print("name " .. i .. " : " .. msg.persons:get(i).name); 
end

msg.strs[1] = "after == 11"
print("===== strs1: " .. msg.strs:get(1))

msg.strs:set(2, "after set 2")
print("===== strs2: " .. msg.strs:get(2))

print("***********************************************************")
local s = pb.serializeToString(msg)
local msg2 = pb.new("person.persons");
pb.parseFromString(msg2, s)
print("uid: " .. msg2.uid);
print("uname: " .. msg2.uname);
print("udescription: " .. msg2.udescription);

for i = 1, msg2.strs:len() do
    print("str " .. i .. " : " .. msg2.strs:get(i)); 
end

for i = 1, msg2.persons:len() do
    --local value = msg2.strs:get(i);
    print("id " .. i .. " : " .. msg2.persons:get(i).id); 
    print("name " .. i .. " : " .. msg2.persons:get(i).name); 
end

msg2.strs[1] = "after == 110000"
print("===== strs1: " .. msg2.strs:get(1))

msg2.strs:set(2, "after set 220000")
print("===== strs2: " .. msg2.strs:get(2))

print("str: " .. pb.tostring(msg));
print("***********************************************************")
```

end

testpb()

**Comment by zhanjunxiong** [comment]
还有一些功能没实现的和不完善的，你可以在这个基础上修改一下。

几年前实现的一个小玩具，居然还能派上用场，感到很意外! haha

**Comment by cokeboL** [comment]
已经很完善了，复杂的也就是message嵌套，嵌套一层的我已经测试过了，递归的方式，多层应该也是ok的；另外就是类型支持，也挺全了，这种我也能改改。小弟目前对c和lua交互的部分，只是皮毛，项目闲的时候再补补课，如果遇到其他的，我再研究和反馈过来^_^

顺路道句：中秋快乐哈！~

**Comment by zhanjunxiong** [comment]
中秋快乐！~

**Comment by ETHybridCLR** [comment]
支持协议兼容吗 服务端新的协议 客户端旧的 有办法兼容吗

**Comment by cokeboL** [comment]
根据proto message格式动态解析的，不存在兼容的说法吧。。。

**Comment by roynutt** [comment]
没看源码，不过动态解析没有性能问题吗

**Comment by chenweijing** [comment]
非常的赞！！！！ 准备使用openresty stream + 楼主的luapb 做个demo玩玩。 顺便问句，老兄，可以加你微信或者微博吗？ 我的微信： 66969721。 感谢老兄做出这么好的东西来。 网易的我看了，头大，太过麻烦了。
